version: '3'
services:
  api:
    image: focuscura/foosballelo-api
    build:
      dockerfile: docker/Dockerfile
      context: api
    volumes:
      # Use local directory for faster development
      - ./api/:/app
    environment:
      - MONGODB_HOST=db
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mongo:3.6
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data: {}
