version: '3'
services:
  api:
    image: focuscura/foosballelo-api
    build:
      dockerfile: docker/Dockerfile
      context: api
    restart: always
    environment:
      - MONGODB_HOST=db
      - VIRTUAL_HOST=foosball-api.schalpoen.nl
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=foosball-api.schalpoen.nl
      - LETSENCRYPT_EMAIL=thijs@schalpoen.nl
    depends_on:
      - db
    networks:
      - backend
      - frontend
      - entry
  db:
    image: mongo:3.6
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend
networks:
  frontend: {}
  backend: {}
  entry:
    external:
      name: nginx-proxy
volumes:
  mongodb-data: {}
  nginx_certs: {} # Written by letsencrypt or possibly any other method
  nginx_vhost_config: {} # Needed to respond to letsencrypt challenges
  letsencrypt_challenge_files: {} # To host letsencrypt challenge files
